### PR TITLE
Fix export/import template #296

### PR DESCRIPTION
**Pull request by benloh**
# Summary

Fixes multiple problems with templates:
* Import and export node/edge data was ignoring `hidden` fields, causing errors when loading
* Interim state updates during template import was causing errors as field types were changed (e.g. from `markdown` to `string`)
* Importing a template was causing JSONEditor to revert to the default deprecated schema

Additionally:
* NCNodeTable and NCEdgeTable has been refactored and optimized to reduce state updates and re-renders.
* JSON Editor has now been removed.

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish please confirm that `dev-bl/fix-export` branch fixes 
- [x] #296
- [x] #297 
- [x] #284

**Comment by jdanish** [comment]
This appears fixed.

**Comment by benloh** [comment]
To close this off...there were three problems.
1.  Exporting and re-importing templates were broken due to hidden fields not being exported. #296 #297.  Fixed with #308.
2. Exporting and re-importing were causing errors due to interim state updates as templates transitioned from one type to another #311 [# 284 comment](https://github.com/netcreateorg/netcreate-itest/issues/284#issuecomment-2558114447).  Fixed with #308 in c0ad2541a84fe12ac999e5056d8f5d895d1fa89e.
3. Importing a template with custom fields would cause JSON Editor to revert to predefined schemas, removing the custom fields.  The main comment in issue #284 is an example of the error.  Issue #115 is the proper description.

**Comment by benloh** [comment]
Merging now so that we can clean up the `match-meme-comment` branch.

**Pull request merged**
