### PR TITLE
Feature: Add filters using `&&` or `||` in strings.

### PR DESCRIPTION
**Pull request by benloh**
See #83 

Adds ability to define string filters that use `&&` or `||` in strings.

For example:
```
label [ contains ] "Ben || Joshua"     // matches "ben" or "joshua"
label [ contains ] "scuba && diving"   // matches "likes scuba diving in the Maldives"
label [ contains ] "scuba || swim"     // matches "likes scuba" and "likes swimming"
label [ contains ] "scuba || swim && diving"     // matches "likes scuba diving" but not "likes swimming" because it's missing "diving"
```

A few notes:

* The logic with "does not contain" gets a little screwy.  I think it's correct, but you might check on it.  It evaluates the expression, then returns the negative of the whole expression.
* While typing, a blank will evaluate as true, e.g. while typing `scuba &&` will return true for any nodes that have "scuba", but typing `scuba ||` will match ALL nodes since the blank is always true.

### CODE REVIEW

**Comment by benloh** [comment]
> does not contain logic

Ah, the logic was flawed.  I was applying the "does containt/does not contain" logic to subclause.  Please try again and see if this fixes it.  

>the field has the same issue the search used to. If you type Books && Burning, then place the cursor to change && to ||, press delete and it now reads Books & Burning and the cursor is at the end.  c1ec735dd223bf6617c37564ceea9270408977e5

This has been fixed with [5342dec](https://github.com/netcreateorg/netcreate-itest/pull/105/commits/5342dec8605e9a4d397a11082158a8dd17c89a0d)

**Comment by jdanish** [comment]
That works, thanks! Helped me notice another (maybe new?) issue though. If you type a filter for a string, and then switch contains to --, the filter text should be removed, right?  It does not. Then if you switch -- back to contains it is not recognizing the text immediately. Though if you add to it by a letter, it then functions as expected.

**Comment by benloh** [comment]
> If you type a filter for a string, and then switch contains to --, the filter text should be removed, right? It does not. Then if you switch -- back to contains it is not recognizing the text immediately. Though if you add to it by a letter, it then functions as expected.

Sorry about that.  We actually had that fixed previously, but then another bug was introduced where the cursor position was being lost with state updates (Kalani's issue from a few weeks ago).  This should be fixed now.


> I also just noticed that markdown fields do not appear in the filters, but would assume they appear / use the same functionality as strings. Sorry I didn't catch that before.

Oops.  Good catch.  Markdown fields just use strings to work.  But I had to explicitly add support for filters.  Should be fixed with cb3e3d03472cea0212dc34f3f2d6ff850316b32b

In addition:
* Re-layout Search input field so the "New Node" button will wrap on narrower screens. b174b85be7dac4169e6d38020f58446539e7494d
* Re-order Number filter operators so that the more commonly used "=" appears first.  6c52246813075bdd3210c33ec5a638545b891ab3
* "Clear Filters" button now properly clears operators AND values in filters. bb878d2e20beecff794573ebf7f6a6d711a721eb
* Refactor "FiltersPanel" so that the filter definitions state is retained when expanding or collapsing the FiltersPanel.  399a101bfd50a26fc458674e1a715912777f7eba

**Comment by benloh** [comment]
@jdanish Did you want to add help text in the "More...> Help" panel for using `&&` and `||` in filter searches?  Should I leave that to you?

**Comment by jdanish** [comment]
Debating, so leave it to me. Thanks!

**Comment by jdanish** [comment]
@benloh looks good - go ahead and merge when you are ready!

**Pull request merged**
