### PR TITLE
UI: Minor Changes to EdgeTable, Node Editing

### PR DESCRIPTION
**Pull request by jdanish**
Minor UI fixes including:

1. Edge tab on node display now includes a count of edges 
2. When  you switch to edit mode for node attributes, help text appears inline
3. The source and target nodes in the edge table now have a mouseover (copied from node table) that highlights the relevant node on mouseover.

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish a general tip about code fixes: Given code changes over time, and our refinements on linting, it's not uncommon to find a file that has a ton of tiny linting fixes.  When this happens, we try to start with an intial linting commit to clear out the changes, and then commit your actual code changes separate so that we can see what's changed.  Otherwise, we end up with a commit like 2c7092b769453b41ec01744afc2f277d6bf28287 where you can't decipher what was changed in code vs what was fixed by the linter.

**Comment by jdanish** [comment]
Thanks @benloh. Sorry to be dense, but I am unsure what I would do to avoid this / make it easier?

**Comment by benloh** [comment]
> Thanks @benloh. Sorry to be dense, but I am unsure what I would do to avoid this / make it easier?

No worries.  It's confusing.  Basically if you make a change on a project that has a TON of linting changes, do the commits in two steps.  For example with 2c7092b769453b41ec01744afc2f277d6bf28287:

1. First commit all the linting changes (e.g. all the prettier fixes with formatting, layout, punctuation, etc.) in one commit.  That way we can see the "inconsequential" changes in one place.
screenshot_1312

2. In a second commit, commit the actual changes you made to code, e.g.  the removal of the extra `isAdmin` check.  This will make it much more clear which line of code we're changing, since settings.js actually had 20 or so linting changes.
screenshot_1313

You can also do it in the reverse order. The main idea is that the individual change in the commit remains visible.

**Comment by jdanish** [comment]
Got it. Will do, thanks!

**Comment by daveseah** [comment]
I'm about to pull the dev and handle this pull request @jdanish so I'll be handling the merge conflicts at this point onward.

**Comment by daveseah** [comment]
@jdanish I'm noticing that there's a change to `IsAdmin()` that removes the check for localhost, which I'll modify in the description of this PR.

**Comment by jdanish** [comment]
Ok. The security issue is still in there and likely will be until we rework the entire login / admin. But dealing with it separately makes sense to me. Thanks!

**Comment by daveseah** [comment]
I've removed the change but kept the original change in the code, commented-out with a reference to this PR (#72).

As a priority, we can try to come up with a better interim solution that is more "hack-proof" and not plain text in the source code or URL. This is something we have to think about anyway, so we might implement a workable manual solution involving passwords and secure toke exchange.

I'll write up a new feature

**Comment by jdanish** [comment]
Sounds good! Thanks!

**Comment by daveseah** [comment]
Seems to compile and run, so merging!

**Comment by benloh** [comment]
@jdanish I wanted to confirm that the help for Nodes should now look like this?  e.g. always visible in black text (not the system gray text)?

screenshot_1316

And that you wanted to leave the edge help text centered for now?

screenshot_1317

**Comment by jdanish** [comment]
If you can make it the gray and left justified easily that'd be awesome. I tried but couldn't id the nested css easily so left it until "later" since my main goal was get help text to appear. Definitely, it should not hold up the merge. If it's quick, it'd be awesome to fix. Need an issue?

**Comment by benloh** [comment]
Since this is already merged, I'll create a new issue.  See https://github.com/netcreateorg/netcreate-itest/issues/79

**Pull request merged**
