### PR TITLE
Dev jd/fix number

### PR DESCRIPTION
**Pull request by jdanish**
Made this quick fix to address #118 (the number input field showed a blank rather than a 0, which was confusing when setting it).

### CODE REVIEW

**Comment by jdanish** [comment]
@benloh I went ahead and made the fix so I could avoid disrupting your flow if possible. I don't *think* it has bigger implications, though of course there might be a better long-term fix. But short-term I think this works?  Let me know if there is something different I can test. Or if you prefer to fix this.

**Comment by benloh** [comment]
@jdanish This works, but you lose the ability to distinguish between no value having been entered vs. deliberately setting it to 0.  If that's not important, then this solution is fine.

**Comment by benloh** [comment]
Also, do you want to update this as v1.5.1 and push to `master`?

**Comment by jdanish** [comment]
Ok by me! Yes let’s do that thanks! ----(from my iPhone)Joshua Danishhttp://www.joshuadanish.comOn Jan 8, 2024, at 1:12 PM, benloh ***@***.***> wrote:﻿
Also, do you want to update this as v1.5.1 and push to master?

**Pull request merged**
