### PR TITLE
Feature: Citation Dialog

### PR DESCRIPTION
**Pull request by benloh**
Addresses #86 

This re-implements the ability to cite nodes and edges. Clicking the "Cite Node" and "Cite Edge" buttons will show a dialog with the citation text with a "Copy to Clipboard" button.  Clicking the button will close the window and copy the text to the clipboard.  

This works on most browsers.  Tested on:
* Chrome
* FireFox
* Safari
* DuckDuckGo
* Edge (Windows)

e.g.
screenshot_1362

```
NetCreate Tacitus network, Node: "Nero" (ID 5). Last accessed at 09:26 on 11/29/23.
```
```
NetCreate Tacitus network, Edge: (ID 8), from "Nero" to "Tacitus". Last accessed at 09:27 on 11/29/23.
```

#### NOTES
* Edge definitions (and Node too?) used to have a `Citation` field that would show bibliographic references.  Clicking on the "Cite Edge" field would reference that field.  With the changeover to built-in fields (source, target) and arbitrary attributes fields (everything else), we no longer have the ability to do that, since a `citation` field may or may not exist.  So currently we do not reference the `citation` field.  One possible workaround is to add support that will automatically add any field named `citation` (if it exists) to the citation text, and to ignore the text otherwise.  Should we add that?  Do you want to call it `citation`?  Something else?
For reference, this is what the citation used to look like:
```
                NetCreate {this.AppState('TEMPLATE').name} network, Edge:{' '}
                {this.state.formData.label} (ID {this.state.formData.id}), from &quot;
                {sourceNode.label}&quot; to &quot;{targetNode.label}&quot;.{' '}
                {citation.text}. Last accessed at {this.dateFormatted()}.
```

### CODE REVIEW

**Comment by jdanish** [comment]
I'll let Kalani weigh in here, but my recollection is that the citation was a more elaborated version of the network name, that if we wanted, instead of:

NetCreate Images of Death network, Node: "Comforting" (ID 3). Last accessed at 12:57 on 11/29/23.

We could have it be:

NetCreate Images of Death network from Kalani's class in 2023, Node: "Comforting" (ID 3). Last accessed at 12:57 on 11/29/23.

I haven't really needed it as much, so will defer to @kalanicraig.

Also, Ben - if we did have it it would be at the level of the whole network / template and calling it citation or citation-text would be great, though where it fits in the data structure likely doesn't matter to us. I think the assumption would be if it is there, use it, if not, use the network name as a default as you did. Does that lead to any thoughts about things being hard or problematic to do?

**Comment by jdanish** [comment]
Sorry, also in the prior version the citation > hidden was used to turn off the buttons. That would be nice as a graph-level attribute. That can also be a separate issue for later, though.

**Comment by benloh** [comment]
Sorry, this was a case of long long term memory messing with my more recent long term memory.  You're absolutely right, we do support the citation field.  I think our early versions did use citation fields, but I had forgotten about the fix. 

This should be working now.  The citation field works in conjunction with the network name.  70638b637658acffc7c7308582140c654eebac8a

**Comment by jdanish** [comment]
This all looks good!

**Review by jdanish — APPROVED** [review]

**Pull request merged**
