### PR TITLE
Infrastructure: Update Package Dependencies

### PR DESCRIPTION
**Pull request by daveseah**
NetCreate still uses libraries that were last updated in 2018, which creates dozens of errors and security issues that make it difficult to extend the code base. This PR updates all the relevant packages and the tools that depend on them.

I've split the update into two PRs:

* #75 (this one) is just for library updates, maintaining the current build system
* #76 contains the changes to source code and **new build system**

#### Step 1: Refresh `node_modules`
As this PR makes enormous changes to the underlying packaged library hierarchy, you should start first by issuing this command:
```
rm -fr node_modules && npm ci && npm run dev
```
This will **not remove** any data. The project loaded will be the most recent one set via the `./nc.js --dataset=` command.

#### Step 2: Look for Weirdnesses

Next, **see if anything looks or acts funny**. Note that the `IsAdmin()` method in `settings.js` has been reverted to its default so if you had made a local change to disable it, you'll have to re-apply it.

REPORT FUNCTIONAL PROBLEMS

* take a screenshot showing the issue (phone is ok)
* broadly, what you were changing in the app
* what did you expect to happen
* what happened instead

REPORT VISUAL PROBLEMS

* take a screenshot (phone is ok)
* circle or describe the issue on the screenshot
* describe what you expected it to look like
* confirm that this is an unexpected change from previous versions

## BACKGROUND INFO

Because the packages are so old, there are **breaking changes** that we have to handle. We've reviewed the packages using the `npm outdated` command and reviewed the changelogs for each package. These are located in the new [`_info` folder](https://github.com/netcreateorg/netcreate-itest/tree/dev-ds/package-update/_info) as `package-update.xlsx` and looks like this:

image

### UPDATE STATUS

1. OK - server systems that have no breaking changes
2. OK - client systems that have no breaking changes
3. OK - server systems that have BREAKING changes
4. OK - client systems that might have BREAKING changes. This is notable BOOTSTRAP and REACTSTRAP, but we have maintained within the Bootstrap 4 ecosystem so this should be ok.
5. OK - update REACT, and REACT-ROUTER. *Rather than upgrade React Router, we completely removed it because it frankly is terrible to work with*
6. STALL - update D3 and REACT-FAUX-DOM. *Latest D3 causes brunch to choke, so ignoring*

At this point, we have to update the tool chain because there are so many incompatibilities with brunch and current JS standards.

### CODE REVIEW

**Comment by daveseah** [comment]
## NOTES on PACKAGE UPDATES

* We're already on **React** 16.14.*, which is probably JUST FINE. We don't need to go to React 18 just yet. React 17 was purely a 'infrastructure changes' on the way to React 18.
* **React Router** is the source of the warnings in the Javascript console. Updating to version 6.x shouldn't be a problem because it requires React 16.8+ (condition already met). Just need to handle the breaking changes.

We don't necessarily need to update the following because we know they work, but the goal is to remove outdated _indirect_ dependencies that these packages are using themselves.

* **ReactStrap** is the wrapper for Bootstrap. We are using Bootstrap 4, which means that ReactStrap version 8 is the maximum we can use. 
* For **D3** and **react-faux-dom**, we know these packages are still working with React 16.14, so we have the option of updating.

Some of the system package updates like `hashids` and `fs-extra` have small breaking changes related to the NodeJS support of **ESM** modules, but this is just a matter of changing the import statements.

**Comment by daveseah** [comment]
## NOTES on MODULE IMPORTS

There are several examples of using **require** and **import** in the same source file, mixing commonjs and es-module syntax. Here's an example I saw in `FilterGroupProperties.jsx`

image

Refresher:
* `import` and `export` are used for asynchronous ES6 code
* `require` and `module.exports` are used for synchronous CommonJS code

**You should not be mixing them**, but the amazing thing is that **brunch** compiling this mixed code just fine, as it looks specifically for `require` and `import` and rewrites them. 

When we move to an updated build system, we may have to back and edit these so they are consistent. The NetCreate codebase does have a lot of older code fragments (the use of `var` everywhere is one giveaway) so I'm a bit surprised it works. 

PR #71 has made hundreds of small fixes to almost every source file, but the inconsistent use `import` and `require` wasn't addressed. I think these fixes can wait until after the build system is updated.

**Comment by daveseah** [comment]
## MAJOR CHANGE

I've removed [React Router](https://reactrouter.com/en/main) from NetCreate when I realized that we didn't actually do anything very fancy with it, and it's always been kind of a terrible implementation. Rather than spend hours refactoring our code to fulfill its persnickity requirements to be compatible with React 16.x, I realized I could just write our own route manager which turns a URL like this:
```
http://localhost:3000/#/edit/TESTPROJECT-TESTPROJECT-5P2?admin=true
```
into this:
```
{
  "route": "/edit",
  "scope": "NetCreate",
  "routeProps": { "token": "TESTPROJECT-TESTPROJECT-5P2" },
  "queryVars": { "admin": "true" }
}
```
I also centralized and made consistent the use of `isLocalHost()` and `isAdmin()` as I continue to track down issues resulting from removing ReactRouter and the various unused `app/view/dev-*` test apps, as they aren't really needed anymore and are broken anyway.

**Comment by daveseah** [comment]
Also, I fixed `ncMakeTokens()` so it again properly outputs a _FORMATTED_ list of tokens; there had been a change in Chrome that broke it.

image

**Comment by dsriseah** [comment]
## MISC BUGFIXES

Tracking down issues with incompatibilities from removing ReactRouter, which were possibly bugs that were covered-up by it or hidden by other React-related errors it caused. Also fixed some bugs along the way:

* `IsLocalHost()` now works with `http://127.0.0.1` as well as `http://localhost`
* `Template.jsx` no longer tries to call a non-existent Array function on an HTMLCollection
* `SessionShell.jsx` live tips while typing a login token no longer display bogus information, and force reload in a different way.
* The left-side panel is nudged down by matching the height of the navbar so text is not cut-off

**Comment by daveseah** [comment]
Ready for review. Assigning reviewers!

**Comment by benloh** [comment]
Excellente!  Merge away!

**Pull request merged**
