### PR TITLE
Feature: Filtered Node/Edge Statistics Summary

### PR DESCRIPTION
**Pull request by benloh**
Addresses #84 

## Summary Statistics

* When the FIlter panel is shown, "Showing x/x nodes, y/y edges" is shown immediately at the bottom of the window.
* Defining a filter will update the "Showing..." summary in real time.
* The Filter Summary (gray bar above the graph) will also show the summary statistics even when the Filter panel is collapsed.

## Additional Fixes

* Numeric filters were using string values in the input field, so filters using "id=1" were not working.
* Non-Faded nodes and edges were using default filter transparency levels rather than removing them.
* De-selecting a filter operator now properly clears the value field.  This fixes a bug where deselecting the filter operator would leave the value in the value field, sometimes resultiing in JS errors.

### CODE REVIEW

**Comment by jdanish** [comment]
@benloh It looks like fading is now going to 100% transparent rather than the field in the view? 

Screenshot 2023-11-19 at 5 29 47 PM

**Comment by jdanish** [comment]
Also, hidden edges are still appearing in the node panel on left, and the edges table

**Comment by jdanish** [comment]
Also just noticed this funny side effect when testing ...  the scaling buttons for the graph need to be moved back a layer?
Screenshot 2023-11-19 at 5 42 11 PM

**Comment by benloh** [comment]
> fading is now going to 100% transparent rather than the field in the view?

Sorry.  Bad logic was interfering with counting.  Should be fixed now.

> the scaling buttons for the graph need to be moved back a layer?

Fixed.

> hidden edges are still appearing in the node panel on left, and the edges table

Do you mean that hidden edges should not show up  in the node editor/node editor at all?  So for all intents and purposes if something is filtered out it should never show up in any editor?  Right now the editors refer to the full dataset rather than the filtered dataset (the rationale was that you still want to be able to view and edit a filtered node/edge).

**Comment by jdanish** [comment]
Sorry, I meant they should be faded in highlight and removed in remove, and that functionality is now restored with the recent fix - presumably the bad logic was effecting both appearances.

**Comment by jdanish** [comment]
>  Is it possible to have that say 5? In an ideal world maybe it changes to say "Highlighting 5/120"? The other two displays can maintain "Showing".

I take that back - because the tab name is set in the template, we should stick with showing. However, if we can report just those that are fully visible and not the ones faded that'd be great. Thanks!

**Comment by benloh** [comment]
Sorry, I guess this logic is screwier than I thought.  Nodes and edges were using different thresholds for fading.  I think the node visual fading was correct but the count was wrong. I think this should be fixed now.

**Pull request merged**
