### PR TITLE
Infrastructure: Module Architecture Stage 3

### PR DESCRIPTION
**Pull request by daveseah**
This PR adds the beginning of our **testing framework** as well as some other quality of life features:

* NEW: The [vitest](https://vitest.dev/guide/) test suite is now integrated into the `_ur` build tool, making it possible to add **unit testing** to our addon libraries and run them all at once.
* NEW: The V2 **StateMgr** has been polished-up and ported from GEMSTEP. 
* FIX: While running the NetCreate, saving a file in `_ur` or `_ur_addons` will now force the application to be recompiled and reload. Before, you would have to manually stop/restart.
* ERROR REPORTING: Cleaner error output when a crash bug occurs in `NetCreate.jsx` or other root component. Before, it was difficult to tell what was happening.
* QOL: the integrated terminal will now properly `cd` to the project root directory, even if you are cloning a new terminal while inside the `_ur` directory. Before, it would open the current working directory and display an error.

### 0. INITIALIZING FOR TEST

* after pulling branch, open integrated terminal window
* `npm ci`

This will install the new `vitest` package.

### 1. TRY THE TESTING SYSTEM

* `cd _ur`
* `ur test`

You'll see some information about the current test. There is currently only on, located in `_ur/common/class-statemgr-test.ts`. The testing system will find _any_ `ts` file that ends with `*-test.ts` or starts with `test-*.ts`.

### 2. TEST NETCREATE and STATEMGR CLASS

* `cd ..`
* `npm run dev` and open localhost:3000
* In the console of NetCreate, look for this text indicating successful instantiation of the new StateMgr class
    image

### 3A. TEST AUTOMATIC REBUILD OF _UR CORE

* Make sure that the previous test is still running. We'll make a change to the StateMgr class in `_ur/common/class-statemgr.ts`
* Note in the current console what it looks like.
* Open `_ur/common/class-statemgr.ts` and find the `constructor()`
* Add `console.log('*** I WAS HERE')` and then save the file
* Quickly switch to the integrated VSCODE terminal and observe that the change has been detected, and the libraries are being recompiled without having to manually restart the server.
* Reload the webapp and check the console to see if `*** I WAS HERE` shows up.

### 3B. TEST AUTOMATIC REBUILD OF _UR ADDONS

* Make sure that the previous test is still running. We'll make a change to the `midi-core.ts`file `_ur_addons/midi/`
* See that the app recompiles as in test 3A

### 4. WITNESS ERROR HANDLING CHANGES

* In `NetCreate.jsx`, insert bad syntax in the middle of the constructor function (e.g. `BOO();`)
* On save, the NetCreate app will show an alert describing what to do, pausing the screen so you can open the console window before halting operation into the debugger. 
* Click the OK button.
* In the console window, switch back to the Javascript console output, and see if you can figure out where the error was found. 

### 5. TEST AUTOHOMING INTEGRATED TERMINAL

* Make sure there is only a single integrated terminal and `cd _ur`
* Click the "Split Terminal" button in the upper right of the terminal panel
* You should see that the new terminal is in your project root, with `vs_env` running without error

### OTHER INFORMATION

* split `ursys-lib` bundle into `ursys-core` and `ursys-addons`, which are loaded via `index.ejs`
* added `source-map` library for future help to deal with sourcemaps not pointing to useful locations for debugging. This is because the URSYS core and addon libraries are transformed twice, so the original source maps are not mapped correctly in NetCreate specifically. 
* added `class-op-sequencer` to `ursys-core` with test (unused)

### CODE REVIEW

**Comment by benloh** [comment]
> 3. TEST AUTOMATIC REBUILD OF _UR CORE

Changing and saving `_ur/common/class-statemgr.constructor()` does not trigger a recompile.  The VSC Terminal does not emit any messages after modifying the constructor.

> 5. TEST AUTOHOMING INTEGRATED TERMINAL

When I split the terminal I see:
screenshot_1422


```
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in: /Users/loh/.npm/_logs/2024-02-13T00_51_08_567Z-debug-0.log
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v18.18.2 --silent` to unset it.
vsenv: setting default node v18.16.0

vsenv: adding './' to end of PATH for easier CLI execution in _ur directory!
       (applies only to this shell)
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/loh/.npm/_logs/2024-02-13T00_51_11_158Z-debug-0.log
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v18.16.0 --silent` to unset it.
loh@clickr _ur % 
```

**Comment by dsriseah** [comment]
@Ben

**Test 3** has now been expanded into two parts to resolve the issue that only `_ur_addons` was being watched. This has been expanded to cover `_ur` as well (in practice, no one should be touching `_ur` source files so messed up the test). Grab the latest push to mod-ur.3.

**Test 5** this might be dependent on your machine architecture, plus there was a bug in the terminal string that was preventing it from being set correctly. Try pulling the latest version of the branch.

**Comment by benloh** [comment]
> Test 3

After running `npm run dev`, I get stuck at:
screenshot_1431

**Comment by dsriseah** [comment]
Doh, I forgot about the cheesy integration test in `NetCreate` for StateMgr` class; the method names have been conformed to camelCase standard. I thought no one was using StateMgr and forgot about this.

New commit pushed.

**Comment by benloh** [comment]
All the tests run now except for Test 5

screenshot_1432

**Comment by benloh** [comment]
Running `nvm use --delete-prefix v18.18.2 --silent` seemed to have fixed the error temporarily.  But upon closing and re-opening the terminal, `cd _ur`, and then opening the split, the error happened again.

**Comment by dsriseah** [comment]
> Running `nvm use --delete-prefix v18.18.2 --silent` seemed to have fixed the error temporarily.

Digging into this more, this issue is described as happening on systems with more than one version of `node`, `yarn`, or `pnpm` installed. The `PREFIX` shell variable is set to "" in the output, when it should be pointing to the nvm-managed node binary or _not set at all_... I believe this is a SHELL variable.

It's possible that your shell is set up in such as away that the `PREFIX` is being clobbered. you'll see the "command not found: node" that is what's causing this crash...?

I've pushed a change to attempt to diagnose the issue. It will check for the existence of the nodejs binary in your path and dump diagnostic info if it's not there. This won't fix things, but it might help get to the bottom of it. Worst case, this should at least cause the shell not to emit so many weird errors (and will still work)

TROUBLESHOOTING CHECKLIST 

* [ ] multiple package managers installed (yarn, pnmp)
* [ ] homebrew installation of node messing things up?
* [ ] root `~/.npmrc` overwriting PREFIX?
* [ ] weird bashrc or zshrc overwriting path?

**Comment by benloh** [comment]
With the diagnostic, this is the error/messages:
screenshot_1433

Maybe I need to redo my path?

And in case this is useful:
```
% which node
/Users/loh/.nvm/versions/node/v18.18.2/bin/node
```

**Comment by dsriseah** [comment]
Some thoughts:
Every time the integrated terminal spawns a new shell, it does execute your `.zshrc`. I thought you had `bash` still set as your shell so it is a little surprising. 

[0]
Try opening the `netcreate-itest.code-workspace` file and changing this line from:
```
    "terminal.integrated.defaultProfile.osx": "x86 macos",
```
to
```
    "terminal.integrated.defaultProfile.osx": "generic macos",
```
Then close the workspace and reopen it.

[1]
Perhaps there's something weird with your`.zshrc` that is not working, or you have multiple package managers installed globally (yarn) or have an old `sudo` or `homebrew` installed node. 

[2] 
Diagnostic WITHOUT workspace to determine default behavior of your system
* Open  visual studio again _WITHOUT_ using the workspace. Just open a folder in a new VSCODE instance (CMD-SHIFT-N). 
* open the first terminal. type `pwd` to note the current working directory path. 
* type `echo $0 $PATH`, then `cd ..` to just change the directory
* spawn a second terminal, then type `pwd` and `echo $0 $PATH` there as well
From this I will get an idea of what your default terminal spawning behavior is before the workspace gets involved. 

[3]
Another possibility is that the newer behavior in VSCODE with restoring terminals is getting in the way. I have it turned off. The VSCODE setting can be found by searching for `Persistent Session Revive`; I have mine set to `never`.

[4]
as a point of comparison, here's what my path looks like compared to yours:
```
/Users/dsri/.nvm/versions/node/v18.18.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:./:/Users/dsri/bin/:./:/Users/dsri/bin/:./:/Users/dsri/bin/
```

[5]
Check the version of nvm:
```
nvm --version
```
mine is 0.39.5

[6]
I'm wondering if your `.zshrc` is missing the NVM alias script, but I see that your `NVM_HOME` is set. This is the script that should be in your `.zshrc` at the END of the file
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
The `nvm.sh` script here is what's adding the correct PATH (you can see it in my `PATH` output at the beginning (see [4] above), whereas it seems to be entirely missing from your screenshot).

[7]
Just to be sure, check these lines in your `netcreate-itest.code-workspace` file match this:
```
    "terminal.integrated.profiles.osx": {
      "x86 macos": {
        "path": "/usr/bin/arch",
        "args": [
          "-arch",
          "x86_64",
          "${env:SHELL}",
          "-i",
          "-c",
          "export VSCODE_TERM='x86 shell';cd ${workspaceFolder}; source .vscode/vs_env; exec ${env:SHELL}"
        ]
      },
      ...
    "terminal.integrated.defaultProfile.osx": "x86 macos",
```

---

If the above doesn't reveal anything, I'll rollback the change until I can get a look at your actual computer to see what's different about it. I wonder if Joshua is getting the same error.

**Comment by benloh** [comment]
The problem was my `nvm` version was outdated (0.35.3).  Updating to 0.39.7 fixed the problem.

**Pull request merged**
