### PR TITLE
Feature: Resizable table columns

### PR DESCRIPTION
**Pull request by benloh**
This adds the ability to resize the Node and Edge table column widths by direct manipulation of the UI.

## User Experience
Resizing columns:
* Fixed sizes for built-in fields, other fields split evenly -- The built in node and edge fields have fixed widths (e.g. degree, label, source, type, target, Comments).  The remaining custom arbitrary fields are then evenly distributed.
* Max resize -- Resizing is done essentially between two columns: the current column, and the column to the right.  (We assume the table width is fixed or 100%).  To give you simple, but finer control over resizing columns, you can expand or contract the current column and the next column up/down to a minimum size.  Once you hit the max size, you need to resize other columns to adjust.  (We don't allow you to resize neighboring columns once you've hit the max/min just to simplify the math).

### History

We had successfully used [handsontable](https://handsontable.com/) for project tables in MEME, which handled sorting and resizing columns admirably.  But rendering handsontables in NC proved to be too inefficient: The redraw updates needed for custom rendering the view/edit and comment buttons as well as the Markdown text fields were slow enough to be unusable.  Also, handsontable paginated long table data which made for an awkward use experience.  The overhead introduced by all of the features of handsontable was not worth it.

It was more efficient for us to build custom tables that specifically addressed our sorting and resizing needs.  We emulated the API for handsontable, and isolated the table calls, so if we should change our mind or look for a different table library, it should be relatively easy to swap in a new table library.

### API

Table rendering is implemented via three layers of components:
* `URTable.jsx`
* `NCTable.jsx`
* `NCNodeTable.jsx` / `NCEdgeTable.jsx`

#### `URTable.jsx`

At the core is a generic `URTable.jsx` component that provides a simple table component with sorting and column resizing.  This can be used with ANY table.

#### `NCTable.jsx`

`NCTable.jsx` provides Net.Create-specific sorters and renderers.  Specifically, support for handling `markdown` and `hdate` (historical date) data formats.  `NCTable.jsx` provides the features common to both Node and Edge tables.

#### `NCNodeTable.jsx`/`NCEdgeTable.jsx`

`NCNodeTable.jsx` and `NCEdgeTable.jsx` defines the table data for nodes and edges, specifying:
* the table data format
* the column order
* any custom sorters
* any custom column renderers
* any custom click handlers (e.g. click to view/edit a node or edge, open a comment)

#### Table Data

Table data is defined as a simple JSON object table, e.g.: 
```
[
  { id: 1, label: 'Constantinople', founding: '100 ce' },
  { id: 2, label: 'Athens', founding: '1000 bce' },
  { id: 3, label: 'Cairo', founding: '3000 bce' },
]
```

The table itself is defined via "Column definitions" that specify:
* the columns to be included
* a title for the column
* the data key to use
* width of the column (in pixels)
* type of data (e.g. number, text)
* any custom sorter
* any custom renderer

URTable can handle a number of built-in generic data types:
* numbers
* dates
* text

...along with some Net.Create-specific data types:

* markdown
* hdate (historical date)

#### Column Sorters

Columns can be sorted ascending and descending using standard types: number, text.
Depending on the data format, dates can be handled and sorted as strings (e.g. "October 1, 2023") or numbers (e.g. if using unix timestamps).  

In addition, custom sorters can be defined for specific data types.

* markdown -- Sorts by raw markdown text, but displays rendered HTML (since sorting by html text is at best confusing).
* hdate -- Sorts by interpreted date, but displays raw hdate data (since we want to sort by the interpreted date while still showing what the user entered).

#### Column Renderers

Standard data types will display text as-is.

If the data requires special handling, you need to define a custom renderer.  For example, you can use a custom renderer to show a button or an image based on the table data.

For example, table data `{ id: 0, url: 'http://www.inquirium.net' }` you can use the `url` to render a clickable button. 

## To Do
- [x] Retain column widths when switching back to table view -- currently if you set column widths and then navigate away (e.g. close the table) then re-open the table, the columns revert to their default values.
- [ ] Add `NCTable.jsx` intermediate class between `URTable` and `NCNodeTable/NCEdgeTable`
- [ ] Show sort direction icons

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish I'm hoping that with 962768f230be338c69f526953631f23a59ca2d0d NC is in a stable enough state for you to demo with your teacher on Sept 18.  Please give it a whirl and let me know if there are any urgent issues that need fixing.  There are definitely still things to refine for tables+comments, so feel free to flag those, but please mark it as `p5 urgent` if you'd like it fixed before the 18th.  In the mean time, we're turning back to MEME.

**Comment by jdanish** [comment]
Minor issue - when you resize the column, it reverts as soon as the mouse moves off the table to the graph. Ideally it stays as long as the page is loaded if not beyond.

**Comment by jdanish** [comment]
Also looks like filters no-longer impact table (fading rows, etc).

**Comment by jdanish** [comment]
> Also looks like filters no-longer impact table (fading rows, etc).

This one is urgent, the reverting less-so. I'll be out most of the day and look again tonight. Thanks!

**Comment by benloh** [comment]
Got it. Thanks for testing.  I'll see what I can do.

**Comment by benloh** [comment]
@jdanish Sunday night Sep 15 fixes
* Table columns should retain their widths and sort order across updates (navigating away, adding comments, etc)
* Filter fade and reduce and focus now work again
* Edge selection and edit from the Edge Table now works (hadn't been implemented)
* Hidden node and edge fields are no longer displayed in the tables

There are definitely still issues that need to be fixed and we'll keep chasing them down, but again, please let me know if there are any urgent ones.

**Comment by benloh** [comment]
NOTE 'NCTable` was never implemented.

> NCTable.jsx
> NCTable.jsx provides Net.Create-specific sorters and renderers. Specifically, support for handling markdown and hdate (historical date) data formats. NCTable.jsx provides the features common to both Node and Edge tables.

The `hdate` and `markdown` renderers and sorters are still in `URTable` and still need to be extracted.

See [Replace HandsOnTable with URTable #90](https://github.com/theRAPTLab/meme-2023/pull/90) for addition of sort indicator display.

**Pull request merged**
