### PR TITLE
Feature: Comment Template

### PR DESCRIPTION
**Pull request by benloh**
Comment types were initially defined in `dc-comments.ts`.  In order to make them editable on a per-project basis, we moved the comment type definitions to the project template file.

This adds the ability to define custom comment types for each project via the existing template system.

* Each project can have its own set of comment types.
* If no comment type has been defined in the template.toml file, the system will fall back to using a generic "Comment" type with a single field.

## Comment Type Definition

A comment type consist of:
```
{
   slug: string,
   format: string,
   prompts: [ ...{ format, prompt, options, help, feedback } ]
}
```

Each prompt consists of an array of prompt objects.  e.g. if you want a comment to have two questions, add two prompts:
```
type TCommentPrompt = {
  format: CPromptFormat;
  prompt: string;
  options?: string[];
  help: string;
  feedback: string;
};
```

Formats include:
```
type CPromptFormat =
  | 'text'
  | 'dropdown'
  | 'checkbox'
  | 'radio'
  | 'likert'
  | 'discrete-slider';
```

## To Add a Comment Template

In the interim, comments can be defined using the current project template system.

* Since this is a temporary system, we have not implemented template editing.  You need to edit these prompts by hand.
* NOTE if you make changes to the template, you need to restart the server to load the new template.

This example shows all of the available formats. Just copy and edit these to implement them.

See #133 for the original feature.

Add this to the end of your existing `<yourproject>.template.toml` file:
```toml
# COMMENT TYPES
[[COMMENTTYPES]]
slug = "demo"
label = "Demo"

[[COMMENTTYPES.prompts]]
format = "text"
prompt = "Comment"
help = "Use this for any general comment."
feedback = "Just enter text"

[[COMMENTTYPES.prompts]]
format = "dropdown"
prompt = "How often did you use \"Dropdown\""
options = ["🥲 No", "🤔 A little", "😀 A lot"]
help = "Select one."
feedback = "Single selection via dropdown menu"

[[COMMENTTYPES.prompts]]
format = "checkbox"
prompt = "What types of fruit did you \"Checkbox\""
options = ["Apple Pie", "Orange, Lime", "Banana"]
help = "Select as many as you want."
feedback = "Supports multiple selections"

[[COMMENTTYPES.prompts]]
format = "radio"
prompt = "What do you think \"Radio\""
options = ["It makes sense", "I disagree", "I don't know", "Handle, comma, please"]
help = "Select only one."
feedback = "Mutually exclusive single selections"

[[COMMENTTYPES.prompts]]
format = "likert"
prompt = "How did you like it \"likert\""
options = ["💙", "💚", "💛", "🧡", "🩷"]
help = "Select one of a series listed horizontally"
feedback = "Select with a single click. Supports emojis."

[[COMMENTTYPES.prompts]]
format = "discrete-slider"
prompt = "Star Rating \"discrete-slider\""
options = ["★", "★", "★", "★", "★"]
help = "Select one of a series stacked horizontally"
feedback = "Select with a single click. Supports emojis."

[[COMMENTTYPES]]
slug = "cmt"
label = "Comment"

[[COMMENTTYPES.prompts]]
format = "text"
prompt = "Comment"
help = "Use this for any general comment."
feedback = ""

[[COMMENTTYPES]]
slug = "tellmemore"
label = "Tell me more"

[[COMMENTTYPES.prompts]]
format = "text"
prompt = "Please tell me more"
help = "Can you tell me more about ..."
feedback = ""

[[COMMENTTYPES]]
slug = "source"
label = "Source"

[[COMMENTTYPES.prompts]]
format = "text"
prompt = "Is this well sourced?"
help = "Yes/No"
feedback = ""

[[COMMENTTYPES.prompts]]
format = "text"
prompt = "Changes"
help = "What about the sourcing could be improved?"
feedback = ""
```

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish Please give this a whirl to define your own comment types.

**Comment by jdanish** [comment]
Awesome!  How is the default / pre-selected chosen?  Is it always "comment"?  Not a big deal either way, but checking / we might want it to always default to whatever is top in the doc?

**Comment by jdanish** [comment]
Minor issue, but if you delete a comment type, the alert that it is falling back works great.

Screenshot 2024-07-31 at 10 33 42 AM

However, it remains even after changing comment type, which is confusing.

Screenshot 2024-07-31 at 10 33 55 AM

Though it goes away correctly once saved. So, ideally it goes away once type is changed. If that takes more than a few minutes, though, we can live with this since it should happen quite rarely and doesn't break anything. Just mildly confusing.

**Comment by jdanish** [comment]
This looks great. I have another bug where sometimes the comment window won't close, no error in console, but can't reproduce it with specific steps, so I am marking this reviewed and will file an issue once I track it down. A screen reload fixes it, so it's not a huge deal, but nice to fix if I can reproduce.

**Review by jdanish — APPROVED** [review]

**Comment by benloh** [comment]
[c12721e](https://github.com/netcreateorg/netcreate-itest/pull/236/commits/c12721ecbc4288310f4a6175399f822d6e201f5b) should now remove the error message as soon as you select a different type.

**Comment by jdanish** [comment]
Confirming fix!

**Comment by jdanish** [comment]
Feel free to merge at your leisure

**Pull request merged**
