### PR TITLE
Feature: Historical Date FIeld

### PR DESCRIPTION
**Pull request by benloh**
A general date input field that can support a variety of calendar formats
for historical projects, e.g. 1000 AD, 10,000 BCE.

The intent is to provide a unstructured input field that allows users to enter arbitrary date-related strings that can be parsed by the application well enough to support filtering and sorting.

This is primarily used for data input rather than timestamping. 

The input field itself is intended to be flexible, using the `chrono-node`
library to parse a wide variety of date formats. The component then
interprets the parsed date and offers a selection of formats for the user
to choose from. The selected format is then displayed in the field.  The
user has the option to select the format "as entered" or to choose from a
list of suggested formats based on the parsed date.

Formats are dynamically generated based on the available parsed date, displaying only formats that match the the parsed dimensions. For example, if
the parsed data includes a year, month, and day, the component will offer
a variety of formats including "April 1, 2024" and "2024/4/1". If the parsed
date only includes a year and month, the component will offer formats like
"April 2024" and "2024/4", but not "April 1, 2024" if the day is missing. If the parsed date only includes a year, the
component will offer formats like "2024" and "2024 CE", etc.

Eras are handled via a template. The user can set the era to BCE/CE or BC/AD.
Dates can be entered in any format, e.g. "2024 BCE", "2024 BC", "2024 CE",
but the selected format will use the format defined in the template, e.g.
if the eras format is set to "BCE/CE", entering "1024 ad" will be formatted
as "1024 CE".  (If you select "as entered" as the format you can still use "1024 ad")

For ambiguous years, adding a "CE" or "AD" to the end of the date will
clarify the era. For example, "102" can't be parsed, but "102 ad"
will parse the input as a year.

You can add extra descriptive text to the field.  As long as the field can interpret the date, the exact text doesn't matter.  So you can add other descriptive text as part of the field and sorting and filtering should still work.  This doesn't work if the input can't be interpreted.  And you do have to make sure the interpretation is correct.

The stored value of a historical date field includes:
* The raw input string
* The selected format
The final output is then dynamically generated based on the selection.

## Draft Features

This is a work in progress.

In the current iteration, the app will inject a historical date field into any node so that you can play with how dates inputs are handled.  The demo date fields currently do not save data.  But you can enter date strings and review how the date is interpreted.

Currently eras are hardcoded as "BCE/CE".  Eventually the template system will allow entering "BC/AD" or other designators for years before and after 0.

In the final version, dates fields can be defined via the template anywhere in the app (e.g. as a node or edge field or a provenance field).

## To Test
The main thing to test right now is to focus on whether or not this method of entering dates is workable for historical projects.  Would it be simpler/easier/better to just force year, month, day, era selections?  Or is it useful to able to support arbitrary strings that are interpreted and formatted in a variety of ways?

1. `git checkout dev-bl/historicaldate`
2. `nvm use && npm ci` -- new libraries have been added
3. `npm run dev` -- Any project should work.
4. Log into the network, and create a node.
5. Select the node
6. Note that there is a "Date" field set to "apr 2024" -- this is currently hard coded.
7. Click "Edit" to edit the date field.
8. Try editing the date, e.g. add a "1", change the date to "4/2024" etc. -- The app will show an interpretation of the date (e.g. "month: 4 year: 2024")
9. Select the "Format" menu to see the optional formats for the date.  
10. Select a format.  Note the "Result" field now shows the selected format.  (We can probably simplify this to just show the selected menu item). -- The format options are based on the data that is available.  e.g. if the system can't find a year, then formats with years are not shown.
11. Enter "ad" or "bc" or "bce" to enter era info.
12. Try adding or removing data (e.g. remove month, remove year, add day, etc)
13. Try adding arbitrary text, e.g. "circa 1500 AD".
14. Try entering ambiguous data, e.g. how do you enter the year 10 vs 2010.

Examples:
* `apr`
* `april`
* `apr 2`
* `4/2`
* `2 apr`
* `2/2/22` -- interprets this as `2022`
* `around 100 ad`

Sometimes the system can't interpret the data.  e.g. it's not clear if a two digit number refers to a day or a month or a year.  Usually if you add more identifiers, the system will be able to interpret the date.  e.g.:
* `100 ad`
* `jan 1 100 bc` 

Please play with it to see what you think.  Hopefully this feels more natural and is flexible.

---

## Questions
- [x] Do we need to support times?  timezones?
- [x] Do we need to explicitly support calendars?  e.g. add a field to select "Hebrew" or "Chinese" or "Gregorian" calendars?
- [x] Should the format be always selectable, even when not in edit mode?  e.g. if I open a node, the date would show the stored selected format.  You can change the format only if you edit the node.  This simplifies the interface (you don't need to have an extra menu to select the format in "view" mode.)  OTOH I can see how it could be helpful for some students to be able to view the date in a different format.

### CODE REVIEW

**Comment by jdanish** [comment]
I ran nvm use and npm ci and even tried clearing the cache but I keep getting this error. Is there some other way to force the install or maybe something not committed yet?

Screenshot 2024-07-01 at 8 29 45 AM

**Comment by jdanish** [comment]
>  Do we need to support times? timezones?

No.

>  Do we need to explicitly support calendars? e.g. add a field to select "Hebrew" or "Chinese" or "Gregorian" calendars?

I assume whoever edits the template will build it to reflect the calendar that that field always uses and indicate that in the held text for the field if needed. I assume that if field A is set to effectively be "Gregorian" then Kalani has a date in a "Chinese" calendar format, it's her problem to translate before data entry. We don't want to get into the game of having her say "this is Chinese" and translate on the fly for her. At least, not for the current student-focused implementation (and I don't anticipate anytime soon). 

> Should the format be always selectable, even when not in edit mode? e.g. if I open a node, the date would show the stored selected format. You can change the format only if you edit the node. This simplifies the interface (you don't need to have an extra menu to select the format in "view" mode.) OTOH I can see how it could be helpful for some students to be able to view the date in a different format.

That sounds right to me.

@kalanicraig speak now or ... well wait until the next grant if any of this doesn't work.

**Comment by kalanicraig** [comment]
Agreed on all points. On date standardization: Most projects will
standardize to a single date type and convert anything internal, and we
have a notes field to disambiguate outliers and odd dates. On live date
conversion: no. Editing only; Joshua’s exactly right that we don’t need
that kind of complexity.

**Comment by benloh** [comment]
> I ran nvm use and npm ci and even tried clearing the cache but I keep getting this error. Is there some other way to force the install or maybe something not committed yet?

Sorry.  I think this ought to be fixed now.

Note that this currently does not actually save the date. This is more a demo so you can get a feel for what it's like to enter different values, see how it gets interpreted, and see what kinds of formats are available for the result formatting.  Clicking "Save" does not save anything.

I think there are edge cases where we end up in a bad state (e.g. "undefined" is displayed).  We'll start to chase all of these down once we get the rest of the system in place.

If this implementation feels right I'll start to finish it off.

**Comment by jdanish** [comment]
This seems great. One thing I wasn't clear - are you assuming the format is selected by the template, and so the user sees what they typed, and then if they save they see it formatted?  Or something else?  And are there errors?  It might help if they see the output it'll translate to and / or an error but I think the format choice would be at the template level. If that's the intent, cool, keep on!

**Comment by benloh** [comment]
> This seems great. One thing I wasn't clear - are you assuming the format is selected by the template, and so the user sees what they typed, and then if they save they see it formatted? Or something else? And are there errors? It might help if they see the output it'll translate to and / or an error but I think the format choice would be at the template level. If that's the intent, cool, keep on!

Sorry yeah this is confusing.

Here's what I had in mind:

0. When first creating the project, the template defines the eras display to use "CE/BCE".
1. When you first create a date, you would:
a. Enter a string (e.g. "circa apr 1 100 bc")
b. I decide that I actually want the system to display something more specific, so I select a format, e.g. "100/4/1 BCE"
c. I click "Save"
2. The node is then displayed  in "View" mode, so you see the date field displayed with "100/4/1 BCE" on the screen.  That is also what is displayed in the Node Table.
3. If I edit the node again, I can see the original string "circa apr 1 100 bc", and can select an alternate format.  e.g. I decide that I want to use MM/DD/YYYY so I select "4/1/100 BCE" as the format, click "Save" and then the node VIEW mode then displays "4/1/100 BCE"

Here the idea is that you might one format for one field, but another format for another field.  We don't want to force every single date to use the same format.

It also means that during edit mode you have to make a lot of decisions about how dates are formatted and viewed.  But in the view mode you would just see the selected date.  Edit mode will show errors or mistakes in parsing so you can review the interpreted date and make sure it is displayed in the way you need.  It seems critical that we provide feedback about the interpretation of the value.

Is that too much flexibility?  Would you rather select a single format for all dates?  My concern is that if sometimes your using year-only dates, but sometimes month-year, and sometimes month-day-year, a single format may not be sufficient.  So you necessarily need to select a different format.

**Comment by jdanish** [comment]
OK, great. Our pitch is a compromise which is:

In creating the template, specify the the era, and then each field that is date format includes a view-as in the template. That way if for some reason we want node.date1 to be mm/yy and node.date2 to be m/yyyy or whatever, that works. We would never want node1.date 1 to be a different format than node2.date 1. This also means that ideally kids only have to type something in and see what's what. 

For kids, we think this does what we need. Long-term for historians, we imagine wanting to potentially show them the as-typed without clicking edit but we can table that for now. 

That have what you need?

**Comment by benloh** [comment]
Hmm...maybe I was overthinking this.  I was imagining that nodes might require different formats (e.g. one source might refer to a specific day/month/year while another might reference a rough year), hence the need to support different formats for any node.  If we always wanted to force a particular format for any given node field, then a more straightforward approach would have been to force something like MM/YY ala credit card entry forms.

If I'm understanding the compromise correctly, then what we'll have is something like this:

```
# K12 TEMPLATE
[nodeDefs.date]
type = "hdate"
eras = "BCE/CE"
format = "MM/YYYY"
displayLabel = "hdate"
exportLabel = "HDATE"
help = "Date of event as MM/YYYY"
includeInGraphTooltip = true
isProvenance = false
hidden = false
```
Dates for the K12 template will always be entered and displayed as "MM/YYYY"

For historians we might define it as:
```
# HISTORIAN TEMPLATE
[nodeDefs.date]
type = "hdate"
eras = "BCE/CE"
format = "AS-IS"
displayLabel = "hdate"
exportLabel = "HDATE"
help = "Date of event as MM/YYYY"
includeInGraphTooltip = true
isProvenance = false
hidden = false
```
Dates for historians will display as strings with the option of setting a specific display format or using the string as-is.  The assumption then is that during editing the user will verify that the date is what they intend.

**Comment by jdanish** [comment]
> I was imagining that nodes might require different formats (e.g. one source might refer to a specific day/month/year while another might reference a rough year), hence the need to support different formats for any node.

It is possible that kids / historians have access to a different format (e.g., they might have Apr 10 in one case, and 4/10/2024 in the other), or in the case of kids, just not bother adapting. For that reason we like taking whatever they put in and just formatting it to the output format. For historians, Kalani confirms that while they'll want access to whatever is typed, they'd still want to be able to sort / view based on a consistent format (e.g., always show MM/YYYY or whatever if that is what makes sense for that topic). 

>  The assumption then is that during editing the user will verify that the date is what they intend.

Do you mean they'll just look closely?  What I mean is, if they type 4/10 and we format that as April 10, do they see April 10 or 4/10?  Long term we'd like them to see both so they can verify the conversion is to what they expected or edit.

For kids, I assume sticking with your demo and having an output is easiest. If you were proposing forcing / validating to MM/YYYY then I'd say while that could be cool long-term, it's actually easier / faster to just let them type whatever and adapt it. Long-term we might want to make it a lesson that they need the right format, but short-term we actually just want the date in so we can focus on other things like sorting.

**Comment by benloh** [comment]
>> The assumption then is that during editing the user will verify that the date is what they intend.
>
>Do you mean they'll just look closely? What I mean is, if they type 4/10 and we format that as April 10, do they see April 10 or 4/10? Long term we'd like them to see both so they can verify the conversion is to what they expected or edit.

If the selected format is "April 10", they would see "April 10" in view mode regardless of what the original input value is.  In edit mode, they would still see "4/10" in the input field, and the selected "April 10" format.

So it kind of sounds like for any historical date, we have three parameters for the template:
* era ('bc/ad' vs 'bce/ce')
* format ('4/10' vs 'April 10' etc)
* allowFormatSelection (boolean)

For students then, you might use:
* era: 'bce/ce'
* format: 'April 10'
* allowFormatSelection: false
So a student might enter "4/10" but the output in the node view is always going to be "April 10".  If they edit the field again, they would see the original string "4/10" along with the formatted string "April 10".  Because `allowFormatSelection` is false, students cannot select another format.

But for historians, you might use:
* era: 'bce/ce'
* format: 'April 10'
* allowFormatSelection: true
So a historian might enter "4/10" but they can then select if they want to use a different format for the specific node.  Because `allowFormatSelection` is true, historians can select any other format for that node.  That means the node "Tacitus" might use "56 CE" while the node "Historiae" might use "Jan 1, 69 CE".

**Comment by benloh** [comment]
## Fixed vs Selectable Date Formats

@jdanish Here's one more pass that introduces the ability to define a date field as either using a fixed format or allows you to dynamically select a format based on the recognized date parameters.  The fixed format is intended for students, and the flexible date format is for historians.

#### New Features

* `allowFormatSelection`
The key is the addition of the parameter `allowFormatSelection`.  If `allowFormatSelect=true` then the format menu is displayed.  If false, the date format always uses the defined format.

* `M? / D? / Y?` preview
For fixed formats, we added `M? / D? / Y?` to the previews so that you can get a sense of what the interpreted format looks like.

* I simplified the UI a little, removing the extra "displayed as" field, since the format selection menu essentially shows the same data.

* Dates and selected formats are now saved.

The available date formats are:
```javascript
  AS_ENTERED: 'As Entered',

  // MONTH
  MONTH_ABBR: 'MMM',
  MONTH_FULL: 'Month',
  MONTH_NUM: 'M',
  MONTH_PAD: 'MM',

  // MONTHDAY
  MONTHDAY_ABBR: 'MMM D',
  MONTHDAY_FULL: 'Month D',
  MONTHDAY_NUM: 'M/D',
  MONTHDAY_PAD: 'MM/DD',

  // YEARMONTHDAY
  MONTHDAYYEAR_ABBR: 'MMM D, YYYY',
  MONTHDAYYEAR_FULL: 'Month D, YYYY',
  MONTHDAYYEAR_NUM: 'M/D/YYYY',
  MONTHDAYYEAR_PAD: 'MM/DD/YYYY',
  YEARMONTHDAY_ABBR: 'YYYY MMM D',
  YEARMONTHDAY_FULL: 'YYYY Month D',
  YEARMONTHDAY_NUM: 'YYYY/M/D',
  YEARMONTHDAY_PAD: 'YYYY/MM/DD',
  HISTORICAL_MONTHDAYYEAR_ABBR: 'MMM D, YYYY CE',
  HISTORICAL_MONTHDAYYEAR_FULL: 'Month D, YYYY CE',
  HISTORICAL_MONTHDAYYEAR_NUM: 'M/D/YYYY CE',
  HISTORICAL_MONTHDAYYEAR_PAD: 'MM/DD/YYYY CE',
  HISTORICAL_YEARMONTHDAY_ABBR: 'YYYY MMM D CE',
  HISTORICAL_YEARMONTHDAY_FULL: 'YYYY Month D CE',
  HISTORICAL_YEARMONTHDAY_NUM: 'YYYY/M/D CE',
  HISTORICAL_YEARMONTHDAY_PAD: 'YYYY/MM/DD CE',

  // YEARMONTH
  MONTHYEAR_ABBR: 'MMM YYYY',
  MONTHYEAR_FULL: 'Month YYYY',
  MONTHYEAR_NUM: 'M/YYYY',
  MONTHYEAR_PAD: 'MM/YYYY',
  YEARMONTH_ABBR: 'YYYY MMM',
  YEARMONTH_FULL: 'YYYY Month',
  YEARMONTH_NUM: 'YYYY/M',
  YEARMONTH_PAD: 'YYYY/MM',
  HISTORICAL_MONTHYEAR_ABBR: 'MMM YYYY CE',
  HISTORICAL_MONTHYEAR_FULL: 'Month YYYY CE',
  HISTORICAL_MONTHYEAR_NUM: 'M/YYYY CE',
  HISTORICAL_MONTHYEAR_PAD: 'MM/YYYY CE',
  HISTORICAL_YEARMONTH_ABBR: 'YYYY MMM CE',
  HISTORICAL_YEARMONTH_FULL: 'YYYY Month CE',
  HISTORICAL_YEARMONTH_NUM: 'YYYY/M CE',
  HISTORICAL_YEARMONTH_PAD: 'YYYY/MM CE',

  // YEAR
  YEAR: 'YYYY',
  HISTORICALYEAR: 'YYYY CE'
```

## To Test

Add this to your current test project's `*.template.toml` file and restart the server.
When you open a node, you'll see the two new date fields: the first is flxed, the second is selectable.
You should now be able to save the data.

```.toml
[nodeDefs.date]
type = "hdate"
displayLabel = "Historical Date"
exportLabel = "Date"
help = "Enter a historical date in the format MM/YYYY CE"
format = "HISTORICAL_MONTHYEAR_PAD"
eras = "BCE/CE"
allowFormatSelection = false
includeInGraphTooltip = true
isProvenance = false
hidden = false

[nodeDefs.customdate]
type = "hdate"
displayLabel = "Formatable Date"
exportLabel = "Date"
help = "Enter a historical date using a custom format"
format = "HISTORICAL_MONTHYEAR_PAD"
eras = "BCE/CE"
allowFormatSelection = true
includeInGraphTooltip = true
isProvenance = false
hidden = false
```

## Caveats

The string parsing of the date is a little touchy.  So sometimes you have to play around with the info to get things to display right.  e.g. sometimes two numbers are considered days, sometimes years.  You should try some real world scenarios to see if this is accurate enough to work. e.g.

* Years are not padded, so `April 20 bc` shows as `04/20 BCE`, which can be confusing.  
* If you enter `15 apr 20` you'll get `4/2020 CE`, but if you add `15 apr 20ce` you'll get `4/20 CE`
* You can't actually enter `4/20` as a date.
   * `4/20` becomes `april 20`
   * `4/20ce` becomes `year 20` with no month -- not sure why april is not interpreted.
   * `4/20 ce` becomes `april 20`
   * `04/020 ce` becomes `20 bc`
   * `04/10000 bc` becomes `10000 bc` -- not sure why april is not interpreted.
   * `april 10000 bc` becomes `10000 bc` -- again, `april` is not interpreted
   * `04/0020 ce` does get interpreted as `04/0020 ce` though the year is not padded, so the resulting text is `04/20 CE`.

We're using the `chrono` library, so if we want to be able to handle other situations, we probably need to add or modify our own parser.  This might get really time consuming.

I'm a little on the fence about whether this is a good solution, but I'm hoping with the feedback during editing, it's interactive enough that you can reach a target solution.

**Comment by jdanish** [comment]
I think this works nicely, thanks! I’d likely want to play more with the layout / ordering, but just moving html around stuff. The functionality seems good to me, and I am OK with it being slightly “funny” so long as there is feedback, which there is. It’s good to learn a) the need to match a format, and b) how to look at it. And I think it’s not worth the added work to make it more structured and avoid possible “errors” like the ones you mentioned. SO, let’s move forward!

**Comment by benloh** [comment]
Cool!

> I’d likely want to play more with the layout / ordering

Yeah I went back and forth on that.  I tried putting the input first, but that seemed awkward too.  I'll just clean this up and leave it to you to play with.

**Comment by benloh** [comment]
Confirmed dates work with Provenance

**Comment by jdanish** [comment]
New bug introduced?  I can't access the nodes table. When I click on the tab it now says:

Screenshot 2024-07-21 at 9 30 39 AM

Otherwise, once this works I can share with team for other feedback to finalize the interface.

**Comment by benloh** [comment]
Yeah, still have some cleanup work ahead :)

**Comment by benloh** [comment]
# Feature: Sort by Date in NodeTable and EdgeTable

@jdanish Sorting in NodeTable and EdgeTable should now be working.  A few notes:

* In fields that `allowFormatSelection` it can be difficult to compare dates because they might all be using different formats.  They should still sort by the parsed date starting with year > month > day > hour > minute > second.
* Any field that is missing is treated as the last item, e.g. 
in ascending order:
```
7/15/5 BCE
7/14/5 BCE
7/16/5 BCE
2024/1 CE
05/03 (no year)
05/06 (no year)
```
in descending order:
```
2024/1 CE
7/16/5 BCE
7/15/5 BCE
7/14/5 BCE
05/06 (no year)
05/03 (no year)
```
* If you change the template to add or change a fixed format for a date field, the date field isn't updated until the you edit the field.  e.g. if the current template date format is `04/05`, and you change it to `Apr 5`, the node will continue to show `04/05` until you edit the node and save it.  At that point, it will refresh to show `Apr 5`.

I'm sure there are other situations that I haven't quite caught, but considering how complex this already is, I'm going to err on the side and calling it good enough until we find an outlyer.

Next up: filtering, which I think is going to be even more complicated...

**Comment by jdanish** [comment]
Cool. The crash is now gone.

In the attached example, the two date columns do not sort or show an error. If I sort by the label it re-sorts. If I then try sorting by either date, no change.

Screenshot 2024-07-25 at 5 49 27 PM


> Next up: filtering, which I think is going to be even more complicated...

What do you see as the challenges?  I was thinking we keep it simple initially and offer a comparison of on, before, or after. Use the same matching you have for sorting, and let's assume anything that is not explicit is just filtered out, or make that a template choice (e.g., anything missing the year is always filtered out, or always left in). I realize that's not "easy" but it seems you've already done the hard parts or am I missing something?

**Comment by benloh** [comment]
> In the attached example, the two date columns do not sort or show an error. If I sort by the label it re-sorts. If I then try sorting by either date, no change.

What's the error?

**Comment by jdanish** [comment]
> What's the error?

No error - 1/2020 is before 1/2026 so if I sort they should flip to be one on the top then the other, no?  No change when clicking "Historical Date" (besides the carrot flipping) and no error. Just nothing.

**Comment by benloh** [comment]
Hmm...can you send me the project file and template file?  Let me see if I can duplicate that.

**Comment by benloh** [comment]
@jdanish Sorry, stupid mistake. I missed a file commit.  Please pull and try again.

**Comment by jdanish** [comment]
All good - works as expected now and will continue to tinker.

**Comment by benloh** [comment]
# Feature: Filters for Historical Dates

@jdanish Filters for historical dates have now been implemented for both nodes and edges.

* Enter a historical date via the input string as with the URDateField.
* The inputted value will be evaluated into a parsed date value and displayed.
* Filters use the parsed value for both the filter definition and for the target field.
* Standard mathematical operators are available: >, >=, <, <=, =, !=.
* Date parameters that are not defined in the filter definition are skipped when evaluating filters.  e.g. if the filter is "<= 2024", only year is evaluated, so "jan 2024" and "jan 5 2024" will be match.  (The alternative is that "<= 2024" would be evaluated as "Jan 1, 2024 00:00:00" and so "Jan 2 2024" would not be matched.)
  * This means you can use filters that target a single date parameter, e.g. "< may" to match any date that comes before the month of May for ANY year.
  * And, you can combine parameters, e.g. "< jul 15 2024" will match "jul 14 2024" but not "jul 16 2024".

NOTE: You'll want to watch out for old projects that might use "Date" as a numeric field.  You should be able to detect them because the input fields will show the "increment' and "decrement" arrows and no validation string.

NOTE: Also, while we do have support for time, it's currently only limited to hours, minutes, and seconds.  Timezone can be stored, but is ignored in filtering.

**Comment by jdanish** [comment]
Testing something like your example, 1/1/2026 does not appear if < 2028 but does if < 1/2028 ...  Otherwise looking good so far.

**Comment by benloh** [comment]
> Testing something like your example, 1/1/2026 does not appear if < 2028 but does if < 1/2028 ... Otherwise looking good so far.

This might be one of the potential issues with this approach.  Note that "2028" by itself does not validate.
screenshot_1631

You have to add "ad" to make it show up as a year.
screenshot_1632

We might consider adding some indicator that the date hasn't validated.  e.g. show a red border until the date is valid.  Maybe also show a "No date detected" or some other such message?

**Comment by jdanish** [comment]
Ahh, ok. Is it possible to have a default (AD or BC) from the template?  If not we can put it in the help to say to add that if needed and I think the indicator of it not being valid (yet) is great. I realize we don't want to do an infinite list of "add this as default" but I think AD / CE is uncommon enough to warrant and the rest can be from the help.

**Comment by jdanish** [comment]
After that, let's approve this and move on and finesse after other major priorities are handled (if we have time)

**Comment by benloh** [comment]
The basic problem is that four numbers by itself will not evaluate to a year.  I'm not sure if adding a default "ad" or "bc" will help, unless you're saying that we add the text to the input value -- but that relies on the user not deleting the "ac" and "bc".  I need to do a little more research.  I'm not sure why the year won't be recognized until we add a "ad" or "ce".  It's possible it's related to trying to support years that are not fixed at 4 digits.

So you don't want to add more validation feedback (e.g. red border if not validated yet, "No date detected" message if a date is not found)?

**Comment by jdanish** [comment]
Sorry, I was unclear:

1: Yes, if it is fast / easy, more feedback would be great. If it'll take more than a few hours, let's simplify down?
2: That makes sense. It feels like AD / BC or whatever is just one of those things that may not be central to some education contexts and so somehow handling it would be nice. But I agree, sticking it into the text feels weird. So if there is nothing simpler to get it to just parse the year ...  let's just use the feedback as above.

**Comment by benloh** [comment]
### Additional Feature: Validation

While typing in a date input field, the text will show red until a valid date is detected.
Once a valid date is detected, the text turns black.

#### How to input "year"
* In general, the best approach to entering a year is to add "ad/bc/ce/bce" to the year, e.g. "1 bc" or "1bc" -- Make sure the era comes right after the year, e.g. "ad 1024" will not work.  If you're wanting to enter a year by itself, this is the best solution.
* If you can add another parameter, e.g. month, then years can be recognized if you use 4 digits.
* Use a 4 digit number with another parameter

Valid Years:
```
1bc       -- no space works
1bce
1ad
1ce
1 bc
10 bc
100 bc
1000 bc
10000 bc
apr 1bc
apr 202 ad
apr 2024
4/2024
```

Does not work:
```
10 bc april -- matches year, but skips month
apr 202      -- year not recognized
apr 10000  -- nothing recognized
2024 apr    -- interpreted as april 20th
10000 apr  -- nothing recognized
4/20            -- interpreted as april 20th
4/10000      -- truncates 10,000 to 1,000.
```

#### Alternative Approaches

It is possible to add a parser that can recognize any three digits as a year.  However, doing so requires modifying how refiners work as `chrono` assumes that a number by itself is not a valid date: it automatically removes the matched string (e.g. "1984") as a possible date result.  It's only when you add a second matched component (e.g. "apr 1984", or "04/1984") does it let the matched snippet pass as a parsed result.  See `UnlikelyFormatFilters.js:16` for the line that removes the unlikely result.

Given that you have to add a second parsed component anyway, we may as well stick to using "bc/ad/bce/ce" to differentiate years from other numbers to make it less ambiguous.

**Comment by jdanish** [comment]
Thanks Ben! I think we can accept this now and move forward. It works well and we can tackle superficial tweaks and / or revisiting after we use it some more.

**Review by jdanish — APPROVED** [review]

**Pull request merged**
